### ISSUE TITLE
IsFirstInstance Property is not initially set

### ISSUE THREAD

**Issue by MueckeMa** [HMBSbige/SingleInstance#49]
With the introduction of TryStartSingleInstance the property IsFirstInstance always has the value false. This is misleading because TryStartSingleInstance must be executed for the correct value. This change came from version 5.0.7 to 6.0.0. A solution would be to test the mutex in the constructor. For this, the mutex would have to be tested in the constructor:

```csharp
public SingleInstanceService(string identifier)
{
	CheckIdentifierValid(identifier);
	Identifier = identifier;
	_mutex = new Mutex(true, Identifier, out _ownsMutex);
	if (!_ownsMutex)
	{
		_mutex.Dispose();
	}
}

public bool TryStartSingleInstance()
{
	CheckDispose();
	return _ownsMutex;
}
```

**Comment by HMBSbige** [comment]
I don't know what are you doing.

I change the design for more situations. Did you try to get the IsFirstInstance value before doing TryStartSingleInstance? You may want to see the [Usage](https://github.com/HMBSbige/SingleInstance/wiki/Usage)
